import {StyleSheet} from 'react-native';
import * as Color from '../../../components/config/color';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  cardContainer: {
    height: '70%',
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
    borderTopRightRadius: 120,
    borderBottomLeftRadius: 120,
    backgroundColor: '#f1f0f2',
  },
  imgCardContainer: {
    flex: 0.6,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    width: '100%',
  },
  imgCard: {
    flex: 1,
    width: '100%',
    borderTopRightRadius: 120,
    resizeMode: 'cover',
  },
  titleCard: {
    marginTop: 9,
    fontSize: 36,
    fontFamily: 'Montserrat-SemiBold',
    color: 'black',
  },
  inputCard: {
    flex: 1,
    height: 60,
    textAlignVertical: 'center',
    fontSize: 15,
    borderWidth: 1.2,
    paddingLeft: 12,
    borderRadius: 12,
    color: 'black',
  },
  textCard: {
    fontFamily: 'Montserrat-Light',
    marginTop: 12,
    paddingLeft: 30,
    paddingRight: 3,
    fontSize: 15,
    textAlign: 'left',
    color: 'black',
  },
  btnText: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 21,
    textAlign: 'left',
    color: 'white',
  },
  textContainer: {
    flex: 0.6,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  lineSeparator: {
    marginTop: 9,
    marginVertical: 3,
    width: '36%',
    backgroundColor: 'lightgrey',
    height: 0.6,
  },
  buttonStart: {
    position: 'absolute',
    bottom: 0,
    height: '13%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderTopLeftRadius: 90,
    backgroundColor: Color.darkMagenta,
  },
  firstShadow: {
    position: 'relative',
    top: -80,
    zIndex: -1,
    height: 90,
    width: '83%',
    alignSelf: 'center',
    borderBottomLeftRadius: 120,
    backgroundColor: '#b9b9b9',
  },
  secondShadow: {
    position: 'relative',
    top: -159,
    zIndex: -2,
    height: 90,
    width: '79%',
    alignSelf: 'center',
    borderBottomLeftRadius: 120,
    backgroundColor: '#a3a4a4',
  },
});
